# Generated by Django 4.2.30 on 2026-04-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0003_attendancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='log_type',
            field=models.CharField(blank=True, choices=[('MI', 'Morning In'), ('MO', 'Morning Out'), ('AI', 'Afternoon In'), ('AO', 'Afternoon Out')], max_length=2, null=True),
        ),
    ]
