# Generated by Django 4.2.30 on 2026-04-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0004_attendancelog_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='username',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
