# Generated by Django 4.2.30 on 2026-04-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0005_alter_attendancelog_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly label, e.g. 'HRIS System'", max_length=100)),
                ('url', models.URLField(help_text='Endpoint to call when the hook fires')),
                ('method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET')], default='POST', max_length=4)),
                ('log_types', models.CharField(default='MI,MO,AI,AO', help_text="Comma-separated log types that trigger this hook. E.g. 'MI,AO' or 'MI,MO,AI,AO'", max_length=20)),
                ('custom_headers', models.JSONField(blank=True, default=dict, help_text='Optional JSON object of extra HTTP headers, e.g. {"Authorization": "Bearer token"}')),
                ('timeout', models.PositiveSmallIntegerField(default=5, help_text='Request timeout in seconds')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webhook Config',
                'verbose_name_plural': 'Webhook Configs',
            },
        ),
    ]
