# Generated by Django 4.2.30 on 2026-04-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0006_webhookconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='frappe_error',
            field=models.TextField(blank=True, default='', help_text='Last error message from Frappe HRMS submission attempt.'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='frappe_synced',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this log was successfully submitted to Frappe HRMS.'),
        ),
    ]
