"""
Django settings for face_recognition project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%bm5s@9q^*^d74xkp*i)bfj#+fah-h7g0y**px$)n!)s$dopr('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CORS_ALLOW_ALL_ORIGINS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'face',
]

AUTH_USER_MODEL = 'face.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'face_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'face_config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


SPOOFING_DIR = str(BASE_DIR / "Silent-Face-Anti-Spoofing")
LIVENESS_DETECTION_ENABLED = False

DATA_UPLOAD_MAX_NUMBER_FIELDS = 3000

# Face Recognition Settings
FACE_RECOGNITION_OPTIMIZED = False
FACE_RECOGNITION_TOLERANCE = 0.45

# ---------------------------------------------------------------------------
# Frappe HRMS Integration
# ---------------------------------------------------------------------------
# Fill in the values below to enable automatic Employee Check-in syncing.
# In production, load secrets from environment variables instead of
# hardcoding them here:
#   import os
#   "API_KEY":    os.environ["FRAPPE_API_KEY"],
#   "API_SECRET": os.environ["FRAPPE_API_SECRET"],
# ---------------------------------------------------------------------------
FRAPPE_HRMS = {
    # Base URL of your Frappe / ERPNext site — no trailing slash
    "BASE_URL": "http://192.168.1.129:8001",

    # API credentials (generate via ERPNext > User > API Access > Generate Keys)
    "API_KEY":    "b9898777e9d8303",
    "API_SECRET": "bcdebd7f9c5231d",

    # The Employee docfield whose value matches the facial-recognition username.
    # Most common choices:
    #   "attendance_device_id"  — biometric device ID (recommended)
    #   "name"                  — Frappe employee name (e.g. "EMP-0001")
    #   "employee_number"       — your custom HR employee number
    "EMPLOYEE_FIELDNAME": "name",

    # Label sent to Frappe to identify this kiosk / installation
    "DEVICE_ID": "FACIAL_RECOGNITION_KIOSK_01",

    # Request timeout in seconds (handlers run in a background thread,
    # so this does NOT affect login response time)
    "TIMEOUT": 10,
}
